### ISSUE TITLE
Problem loading custom template tags

### ISSUE THREAD

**Issue by CityguideParis** [RevSquare/django-social-feeds-parser#1]
The error i get when trying to load the page:
ImportError raised loading socialfeedsparser.templatetags.socialfeedsparser_tags: No module named models

**Comment by omji** [comment]
Thanks for notifying this. Are you using python 3? I have pushed a fix here: 8074982348c71c3a825fecf585eac6a13f1e3c90

Can you please let me know if it resolves the issue for you? If not can you please let me know what version of Python and eventually django you are using?

**Comment by omji** [comment]
As there was no follow up for a month, i am closing the issue.

**Comment by CityguideParis** [comment]
Thank you very much  for the fix.
ana
